require('lazy').setup({
  { import = 'plugins.lsp' },
  { import = 'plugins.treesitter' },
  { import = 'plugins.ui' },
  { import = 'plugins.git' },
  { import = 'plugins.debug' },
  { import = 'plugins.misc' },
  { import = 'plugins.telescope' },
  { import = 'plugins.autopairs' },
  { import = 'plugins.gitsigns' },
  { import = 'plugins.indent_line' },
  { import = 'plugins.lint' },
  { import = 'plugins.neo-tree' },
  { import = 'plugins.flash' },
  { import = 'plugins.fidget' },
  { import = 'plugins.vim-tpipeline' },
  { import = 'plugins.vim-tmux-navigator' },
  { import = 'plugins.tabout' },
  { import = 'plugins.move' },
  { import = 'plugins.float-terminal' },
}, {
  checker = { enabled = true },
  change_detection = { notify = false },
})
